# OTLP Collector Config with HTTP Exporter
# Ref:
#  https://opentelemetry.io/docs/collector/configuration/
#  https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
#  https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/local/otel-config.yaml

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
#  pprof:
#    endpoint: 0.0.0.0:1777
#  zpages:
#    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318  # where your apps send OTLP logs

processors:
  filter/http_only:
    error_mode: ignore
    logs:
      log_record:
        # Drop everything that does NOT look like an HTTP log
        - 'attributes["http.method"] == nil'
  memory_limiter:
    check_interval: 5s
    limit_percentage: 75
    spike_limit_percentage: 15
  attributes/global:
    actions:
      - key: service.environment
        value: production
        action: upsert
  batch:
    send_batch_max_size: 8192
    send_batch_size: 2048
    timeout: 5s

exporters:
  # New-style name in upstream Collector
  otlphttp:
    # Base endpoint; Collector will use /v1/logs for logs
    #logs_endpoint: "https://logs.channelseal.com/v1/otel-logs" #external
    logs_endpoint: "http://host.docker.internal:8000/otel-http-export-logs" #internal use
    # Optional settings
    compression: none
    encoding: json
    timeout: 10s
    sending_queue:
      enabled: true
      queue_size: 8000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    tls:
      insecure: true #TODO: make it secure
    headers:
      CS-Org-Id: "10000000" #Replace with your ChannelSeal Organization Id

  debug:
    verbosity: normal  # or detailed / basic

service:
  telemetry:
    logs:
      level: info
#    metrics:
#      address: 0.0.0.0:8888   # Prometheus scrape target for collector self‑metrics[web:68]
  extensions: [health_check] #pprof, zpages
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes/global, filter/http_only]
      exporters: [otlphttp, debug]
