# OTLP Collector Config with HTTP Exporter
# Ref: https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
# Ref: https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/local/otel-config.yaml

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318  # where your apps send OTLP logs

processors:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  batch: {}

exporters:
  # New-style name in upstream Collector
  otlphttp:
    # Base endpoint; Collector will use /v1/logs for logs
    #logs_endpoint: "https://api.channelseal.com/otel-http-export-logs" #external
    logs_endpoint: "http://host.docker.internal:8000/otel-http-export-logs" #internal use
    # Optional settings
    compression: none #gzip
    encoding: json #proto
    tls:
      insecure: true #TODO: make it secure
    headers:
      CS-Org-Id: "10000000" #Replace with your ChannelSeal Organization Id

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
